# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Church in Manila History Center
email: info@churchinmanila.org
description: > # this means to ignore newlines until "baseurl:"
  An audio guide for Church in Manila History Center
baseurl: "/en" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://historycenter.churchinmanila.org/" # the base hostname & protocol for your site
logo: "/assets/img/logo/audio-guide.png"
twitter_username: churchinmanila
github_username:  churchinmanila
menu_heading: "Select another stop"
index_page_text: "Select an audio guide stop to begin."
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.12
